[build]
builder = "dockerfile"

[deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
ENVIRONMENT = "production"
CORS_ALLOWED_ORIGINS = "https://hiros.online,https://www.hiros.online"
